// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeUP0SxFZLQtGV5uMIbpmgcs3zkl5BI9w',
    appId: '1:708028666314:web:e6313219d9c7ff8edbff33',
    messagingSenderId: '708028666314',
    projectId: 'coach-notes-2d8b0',
    authDomain: 'coach-notes-2d8b0.firebaseapp.com',
    storageBucket: 'coach-notes-2d8b0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA5MjDjfw8XkdOIMEv13a5z3izLNNqEIs',
    appId: '1:708028666314:android:a0d34a656d30efdadbff33',
    messagingSenderId: '708028666314',
    projectId: 'coach-notes-2d8b0',
    storageBucket: 'coach-notes-2d8b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB35e91PaisFt72AWcckLA4umqRpsa36zM',
    appId: '1:708028666314:ios:935bd03f3547cbfddbff33',
    messagingSenderId: '708028666314',
    projectId: 'coach-notes-2d8b0',
    storageBucket: 'coach-notes-2d8b0.firebasestorage.app',
    iosBundleId: 'com.example.coachNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB35e91PaisFt72AWcckLA4umqRpsa36zM',
    appId: '1:708028666314:ios:935bd03f3547cbfddbff33',
    messagingSenderId: '708028666314',
    projectId: 'coach-notes-2d8b0',
    storageBucket: 'coach-notes-2d8b0.firebasestorage.app',
    iosBundleId: 'com.example.coachNotes',
  );
}
